// Email capture and PDF delivery endpoint
// For full email delivery, add RESEND_API_KEY to Vercel environment variables
// and install resend: npm install resend
// For now, this captures the email and returns success so the frontend can trigger print

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { email, toolName, evaluationHtml } = req.body;

  if (!email || !email.includes("@")) {
    return res.status(400).json({ error: "Valid email is required" });
  }

  // Log the captured lead
  console.log(`[LEAD CAPTURED] Email: ${email}, Tool evaluated: ${toolName}, Time: ${new Date().toISOString()}`);

  // --- Optional: Send email via Resend ---
  // Uncomment this block once you add RESEND_API_KEY to Vercel env vars
  // and run: npm install resend
  //
  // const { Resend } = require('resend');
  // const resend = new Resend(process.env.RESEND_API_KEY);
  //
  // try {
  //   await resend.emails.send({
  //     from: 'Product Research Tool <reports@yourdomain.com>',
  //     to: email,
  //     subject: `Tool Evaluation: ${toolName} — Product Research Tool by Cash & Cache`,
  //     html: `
  //       <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
  //         <div style="background: #0A1628; padding: 20px; border-radius: 8px; margin-bottom: 16px;">
  //           <h1 style="color: #fff; font-size: 18px; margin: 0;">${toolName} — Evaluation Report</h1>
  //           <p style="color: rgba(255,255,255,0.6); font-size: 13px; margin: 8px 0 0;">Generated by Product Research Tool</p>
  //         </div>
  //         <p style="color: #4A5568; font-size: 14px;">Your evaluation report is attached to this email. You can also save it as PDF from the tool directly.</p>
  //         <p style="color: #4A5568; font-size: 14px;">Want more structured AI tool evaluations? <a href="https://cashandcache.substack.com/subscribe" style="color: #00B8D9;">Subscribe to Cash & Cache</a>.</p>
  //         <hr style="border: none; border-top: 1px solid #E2E4E9; margin: 20px 0;" />
  //         <p style="color: #8892A4; font-size: 11px;">Product Research Tool by Cash & Cache — cashandcache.substack.com</p>
  //       </div>
  //     `,
  //   });
  // } catch (emailError) {
  //   console.error('Email send failed:', emailError);
  //   // Don't block the user — still return success so they can print
  // }

  return res.status(200).json({
    success: true,
    message: "Email captured. PDF ready to download.",
  });
}
